name: Tests

on:
  pull_request:
    branches: [ develop ]
    types: [opened, synchronize]    
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v2
      - uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '3.6.11'
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - name: "Echo versions"
        run: |
          echo "node: $(node -v)"
          echo "npm: $(npm --version)"

      - name: install
        run: npm ci

